# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Test package

on: 
  push:
    branches:
      - main
      - develop
      - test

jobs:
  test_linux:
    name: Test Linux

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8.17, 3.9.13, 3.10.11, 3.11.4]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python # Set Python version
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build mazikeen
      run: |
        pip install -e ".[testing]"
    - name: Test with unittest
      run: |
        cd tests
        python -m unittest discover . -p '*_test.py'

  test_windows:
    name: Test Windows

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.9.13, 3.10.11, 3.11.4]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python # Set Python version
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build mazikeen
      run: |
        pip install -e ".[testing]"
    - name: Test with unittest
      run: |
        cd tests
        python -m unittest discover . -p '*_test.py'